### ISSUE TITLE
problem with injected css and js in python file

### ISSUE THREAD

**Issue by sopa0** [jmbuhr/otter.nvim#174]
Hi,
Currently working with FastHTML, which is a python lib, which requires me to sometimes write css and js in .py files.
Something like that: 

For css (example pulled from the FastHTML docs)

```python
from fasthtml.common import * 

app, rt = fast_app(
    pico=False,
    hdrs=(
        Link(rel='stylesheet', href='assets/normalize.min.css', type='text/css'),
        Link(rel='stylesheet', href='assets/sakura.css', type='text/css'),
        **Style("p {color: red;}")**
))
```

For js (example pulled from [this repo](https://github.com/AnswerDotAI/fasthtml-example/tree/cebcde6090f93a9fc239a9a5ed1895d9c49a49ef/3d-component)

```javascript
def playing_card(suit, rank):
    "Create a flippable playing card component for any card"
    front = _card_bg(f'fronts/{suit}_{rank}')
    back = _card_bg('backs/blue2')
    return Div(
        Div(cls="front"), Div(cls="back"),
        StyleX('playingcard.css', front=front, back=back),
        Script("me().on('click', ev => me(ev).classToggle('flipped'))"),
        cls="playing-card")

```

Basically, some utility callables take in a str as a parameter, which contains another language. I made a few TS injection queries, which are in my after/queries/python/injections.scm:
```
;; extends
((call
  function: (identifier) @function_name (#eq? @function_name "Style")
  arguments: (argument_list
    (string
      (string_content) @injection.content)))

  (#set! injection.language "css"))

((call
  function: (identifier) @function_name (#eq? @function_name "Script")
  arguments: (argument_list
    (string
      (string_content) @injection.content)))

  (#set! injection.language "javascript"))

((call
  function: (identifier) @function_name (#eq? @function_name "On")
  arguments: (argument_list

    (string
      (string_content) @injection.content))

  (#set! injection.language "javascript")))
```
I know the queries work because I get proper highlighting for the injected langs

Now, when I run :lua require("otter").activate({"css", "javascript"}, true, true) in my python files, I get no lsp features, no autocomplete, even though otter is running, and running :lua require("otter").export() gives me correct contents for the hidden buffers (each contain their respective css and javascript content)

as far as my config goes, it's the basic one from the docs:
```lua
{
    'jmbuhr/otter.nvim',
    dependencies = {
      'nvim-treesitter/nvim-treesitter',
    },
    opts = {},
},

```

So, is there anything I can do on my end to fix it, or is it an issue with the plugin?
Thanks

**Comment by jmbuhr** [comment]
Your injection doesn't work for me on the css part, but it does for your js example, for which I then also get e.g. completion:
![image](https://github.com/user-attachments/assets/fd367caa-0bd1-4d54-855f-61c2a6c3b03c)

I assume you have language servers installed and configured with lspconfig for css and js respectively?

I do notice that requests seem to be offset by 1 character, so e.g. the hover for `ev` is available over `v` and the `space` to the right of it but not over the `e`:
![image](https://github.com/user-attachments/assets/6855ccfa-cce5-4090-b946-0c15ab4bd3f2)
So that part is probably a bug in otter.

**Comment by jmbuhr** [comment]
btw. `otter.activate()` without arguments is enough, it uses all the languages it can find by default and the other two args are also the default.

**Comment by jmbuhr** [comment]
Ah, your css example had additional `**`, those have to be removed to get valid syntax and thus also injections.

**Comment by sopa0** [comment]
> Ah, your css example had additional `**`, those have to be removed to get valid syntax and thus also injections.

Ah yeah right, probs a mistake on my part
As far as the lsp situation, I got both cssls and vtsls working in their respective filetypes
![image](https://github.com/user-attachments/assets/c5c4ff3d-8c31-457e-97f4-33af5ae8b1d4)
![image](https://github.com/user-attachments/assets/f7bfe80e-9d92-4572-b4ca-4d3b1d321370)


Css is somewhat working, in the context of a multi-line string:
![image](https://github.com/user-attachments/assets/1998b5a4-6227-4481-adda-0b4f32a45b78)

Though, on the first autocomplete, it indents like this and stop working until I close and reopen the file:
![image](https://github.com/user-attachments/assets/566dd8d0-feb0-49af-abf0-24a0db2c7216)

Interesting that the js lsp in Script("") works for you, not the case for me, I'll try making a minimal config with otter only see if it's one of my plugins giving me a hard time

**Comment by sopa0** [comment]
In Script("") I seem to get python lsp instead:
![image](https://github.com/user-attachments/assets/ae5309d8-4d0b-45b8-a9d7-676f9d59bc50)

(got both ruff and pyright)

**Comment by sopa0** [comment]
Found the issue for cssls in my lsp logs:


[WARN][2024-09-02 14:45:32] ...m/lsp/client.lua:1025	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[ERROR][2024-09-02 14:45:32] ...lsp/handlers.lua:624	"Unhandled exception: MethodNotFound\nError: MethodNotFound\n    at handleResponse (/home/sopa0/.local/share/nvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:595:48)\n    at handleMessage (/home/sopa0/.local/share/nvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:432:20)\n    at Immediate.<anonymous> (/home/sopa0/.local/share/nvim/mason/packages/css-lsp/node_modules/vscode-langservers-extracted/node_modules/vscode-jsonrpc/lib/common/connection.js:402:30)\n    at process.processImmediate (node:internal/timers:483:21)"
